### PR TITLE
Update to new JuMP version

### PR DESCRIPTION
**Pull request by mitchphillipson**
In the old version of JuMP the function `value(::Function , ::Number)` was undefined in JuMP so was overwritten in MPSGE.jl. The new version of JuMP fixes this.

### CODE REVIEW

**Comment by EliLazarus** [comment]
I think this should be its own branch and PR, without all the documentation changes mixed in.

**Comment by mitchphillipson** [comment]
Gosh darn it. I went to update the documentation with this change and managed to update this branch too. I'll fix it.

**Comment by mitchphillipson** [comment]
Okay, it's fixed now. My mistake :|

**Comment by EliLazarus** [comment]
Ok great. All good.

**Pull request merged**
